### ISSUE TITLE
Allow subsets of config to come from secrets / config maps

### ISSUE THREAD

**Issue by mmihic** [cashapp/misk#185]
We don't want to keep credential information as part of committed configuration, but do want it to be loaded and bound into config properties so it looks like any other config. This probably means we want to have some mechanism to supply config properties from k8s secrets or config maps. Internally we have a special "directive" in YAML which tells the config processor to resolve a given field by loading a property from another file, where that file is mounted as a secret/config map. e.g.

````yaml
datasources:
    exemplar:
        username: %secret('/app/exemplar/secrets/exemplar_production_db.yaml#username')
        password: %secret('/app/exemplar/secrets/exemplar_production_db.yaml#password')
````

Dunno if we want to keep something like this, or have some mechanism more directly tied into k8s config maps but we need a similar type of capability to keep credentials in protected secret storage.
